CrimeAnalysis/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('RegisterCrime.html/', views.registerCrime, name='registercrime'),
    path('addcrime/', views.addcrime, name='addcrime'),
    path('index.html/', views.index, name='index'),
    path('SearchCrime.html/', views.searchcrime, name='searchcrime'),
    path('UpdateCrime.html/', views.updatecrime, name='updatecrime'),
    path('searchcrime/', views.searchc, name='searchc'),
    path('ShowCrime.html/', views.show, name="show"),
    path('register.html/', views.register, name="registeruser"),
    path('login.html/', views.login, name="loginu"),
    path('updateuser.html/', views.updateuser, name="updateuser"),
    path('viewuser.html/', views.viewusers, name="viewusers"),
    path('chartjs.html/', views.chartjs, name="chartjs"),
    path('ViewCharts.html/', views.ViewCharts, name="ViewCharts"),
    # path('basic-table.html/', views.basictable, name="basictable"),
    path('viewcriminal.html/', views.viewcriminals, name="viewcriminal"),
    path('criminaldetail.html/', views.criminaldetail, name="criminaldetail"),
    path('showupdate_combined/', views.showupdate_combined, name='showupdate_combined'),
    path('UpdateCrime.html/<str:parameter>', views.updatecrime, name='updatecrime'),
    #path('showupdatecrime.html/', views.showcriminaldata, name='showcriminaldata'),
    path('showupdate/<str:param1>/<str:param2>/<str:param3>/', views.showupdate, name='showupdate'),
    path('showcrimedata/', views.showcrimedata, name='showcrimedata'),
    path('deletecrimedata/', views.deletecrimedata, name='deletecrimedata'),
    path('displaycrime/<str:param1>/', views.displaycrime, name='displaycrime'),
    path('displaycrime/', views.displaycrime, name='displaycrime'),
    path('predicthotspot/', views.predicthotspot, name='predicthotspot'),
    path('searchchart.html/', views.searchchart, name='searchchart'),
    path('searchchartresult.html/', views.searchchartresult, name='searchchartresult'),
    path('welcomeMsg.html/', views.welcomeMsg, name='welcomeMsg'),
    path('predicthotspotcall/', views.predicthotspotcall, name='predicthotspotcall'),
    path('searchcrimeresult.html/', views.searchcrimeresult, name='searchcrimeresult'),
    path('readFromVoiceSeparate/<str:param>/', views.readFromVoiceSeparate, name='readFromVoiceSeparate'),
    path('statuschangedata/', views.statuschangedata, name='statuschangedata'),
    path('statuschangedata/displaycrime/<int:param1>/', views.displaycrime, name='displaycrime'),
    path('futurehotspots.html/', views.futurehotspots, name='futurehotspots'),    
    path('predicthotspots_of_date/', views.predicthotspots_of_date, name='predicthotspots_of_date'),
    path('sampleurl/', views.sampleurl, name='sampleurl'),
    
    
   # path('UpdateCrime.html/showupdatecrime.html/<str:param1>/<str:param2>/<str:param3>/', views.showupdate, name="showupdate"),
]

main/views.py
from django.shortcuts import render, redirect
from .models import CrimeOperations
from .models import UserOperations
from django.contrib.auth.decorators import login_required
import json
import re
import joblib
from django.conf import settings
import os
from django.http import HttpResponse
import pyttsx3
import speech_recognition as sr
from time import sleep
import pymongo
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import numpy as np    
from datetime import datetime
from django.http import JsonResponse
from sklearn.metrics import mean_squared_error
from collections import Counter
import threading
from datetime import datetime, timedelta


# import numpy as np
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense




def speak(Text):
    engine = pyttsx3.init("sapi5")
    voices = engine.getProperty('voices')
    engine.setProperty('voice', voices[0].id)
    engine.setProperty('rate', 170)
    print("")
    print(f"You : {Text}.")
    print("")
    engine.say(Text)
    engine.runAndWait()

def speechrecognition(text):
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening.....")
        speak(text)
        print(text)
        r.pause_threshold = 1
        audio = r.listen(source,0,8)

    try:
        print("Recognizing....")
        speak("Recognizing.....")
        query = r.recognize_google(audio,language="en")

        print(f"==> Vedant : {query}")

        if "skip" in query:
            return ""
        
        
        if "exit" in query:
            return "terminate"
            
        return query.upper()
    except:
        speak("Dose Not Recognized Properly, Please Repeat Again.....")
        speechrecognition(text)

def readFromVoiceSeparate1(request):
    data = {}
    speak("Welcome Sir, I am Sarthi")
    sleep(0.5)
    speak("Your Voice Assistant")
    sleep(0.5)
    speak("Please tell me following details...")
    txt = speechrecognition("Listeneing for First Name")
    data['fname'] = txt
    txt = speechrecognition("Listeneing for Last Name")
    data['lname'] = txt
    try:
            
        txt = speechrecognition("Listeneing for Age")
        data['age'] = txt
    except:
        print("invalid age..")
    txt = speechrecognition("Listeneing for Date of Birth")
    data['dob'] = txt
    txt = speechrecognition("Listeneing for Gender")
    data['gender'] = txt
    try:
        txt = speechrecognition("Listeneing for Phone Number")
        txt = txt.replace(" ", "")
        if len(txt) < 10:
            need = 10-len(txt)
            txt = txt[:len(txt)]+"0"*need
        elif len(txt) > 10:
            txt = txt[:9]
        
    except:
        print("invalid phone number")
    data['phone'] = txt
    txt = speechrecognition("Listeneing for Height")
    data['height'] = txt
    txt = speechrecognition("Listeneing for Address")
    data['addrs'] = txt
    txt = speechrecognition("Listeneing for FIR Number")
    data['FIR_No'] = txt
    txt = speechrecognition("Listeneing for Type of Crime")
    data['Type_of_Crime'] = txt
    txt = speechrecognition("Listeneing for Number of Person Involve")
    data['Number_Of_Person_Involve'] = txt
    txt = speechrecognition("Listeneing for Weapons use for Crime")
    data['Weapons_use_for_Crime'] = txt
    txt = speechrecognition("Listeneing for Date of Crime")
    data['Date_of_Crime'] = txt
    txt = speechrecognition("Listeneing for Time Period of Crime")
    data['Time_Period_of_Crime'] = txt
    txt = speechrecognition("Listeneing for Vehicle Used")
    data['Vehicle_use'] = txt
    txt = speechrecognition("Listeneing for Vehicle Number")
    data['Vehicle_No'] = txt
     

    return data


def readFromVoiceSeparate(request,param):
    data = {}
    
    txt = speechrecognition("Listeneing for "+param)
    if txt == None:
        txt = ""

    if "Phone" in param or "Age" in param or "Aadhar-Number" in param or "Height" in param or "F-I-R-Number" in param or "Number-Of-Person-Involved" in param:
        txt = txt.replace(" ", "")
        txt = re.findall(r'\d+', txt)

        # Convert the list of strings to a list of integers
        txt = [int(num) for num in txt]
        
    
    print("PARAM:- ",param)
    print("VALUE:- ",txt)

    data['query'] = txt

    return JsonResponse(data)

def readDescriptionFromVoice(request):
    data={}
    stat={}
    text = ""
    text_predict = ""
    if request.POST.get('submitbtn'):
        text_predict = request.POST.get('crime_description')
        text = text_predict
        print("text = ",text)
    else:
        text = speechrecognition("Listening For Crime Description")
        text_predict = text
    # Load the pre-trained model
    svm_type_classifier, tfidf_vectorizer = joblib.load('C:/CrimeAnalysis_ML/trained_model.joblib')
    def classify_description(description):
        tfidf_new = tfidf_vectorizer.transform([description])
        predicted_type = svm_type_classifier.predict(tfidf_new)[0]
        return predicted_type
    def preprocess(text):
        text = re.sub(r'[^\w\s\']',' ',text)
        text = re.sub(r' +',' ',text)
        return text.strip().lower()
    # text_predict = """In a quiet suburban neighborhood, a daring burglary unfolded under the cover of darkness. A skilled thief, equipped with tools of the trade, discreetly 
    # entered a residence through an unlocked back door. Moving with calculated precision, the intruder swiftly ransacked the home, absconding with valuable jewelry and electronic devices.
    # The residents, unaware of the intrusion until morning, were left shocked and violated by the audacious crime that had taken place within the sanctity of their own home. 
    # Law enforcement was promptly notified, initiating an investigation into the burglary that left the community on edge."""
    text_predict = preprocess(text_predict)
    text_predict = text_predict.replace("\n", " ")
    # text_predict = "attempted to murder a woman from a car driver"
    predicted_type = classify_description(text_predict)
    # Display the predicted Category and Type
    
    predicted_type = predicted_type.upper()
    data['type'] = predicted_type
    
    print(f"Predicted Type: {predicted_type}")
    ####################Crime Description Data Extraction
    import spacy
    nlp = spacy.load("en_core_web_sm")
    # text = """In the quiet neighborhood of Maple Street, a heinous crime occurred. The suspect, John Doe, a 35 year old male with a date of birth on 4/15/1987, was involved in an armed robbery. The crime took place on 7/12/2023 between 2 PM and 4 PM.
    # The suspect, armed with a firearm, robbed a convenience store at 123 Elm Street. The FIR number for the case is FIR-2023-567. Two other individuals were part of the crime, one wielding a knife and the other acting as the getaway driver.
    # The getaway vehicle, a red sedan with license plate number ABC-123, had three people inside. The driver was a tall man of 165cm (5'5"), wearing a black cap and sunglasses. The passenger in the front seat was a woman with a blue scarf, and in the back seat, there was a man in a green jacket.
    # The crime spot was near a prominent landmark, the city park. The pincode for the area is 567896. The incident was captured on CCTV cameras, and the police are actively investigating. The latitude and longitude of the crime spot are 40.7128 N and 74.0060 West.  Phone Number is 9922334455
    # """
    # text = "Rajesh Kumar attempted to murder Pravin"
    import string
    def remove_punctuation(text):
        # Define a translation table that excludes periods (full stops)
        translator = str.maketrans('', '', string.punctuation.replace('.', ''))
        
        # Apply the translation to the text
        text = text.translate(translator)
        
        return text
    # Example usage:
    text_with_punctuation = text
    text = remove_punctuation(text_with_punctuation)
    # print("text = ",text) 
    doc = nlp(text)
    
    
    pattern = r'\d+'
    names = []
    
    first_name = ""
    last_name = ""
    # for ent in doc.ents:
    #     if ent.label_ == "PERSON":
    #         match = re.search(pattern, ent.text)
    #         if not match:
    #             print("entities: ",ent.text)
    
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            match = re.search(pattern, ent.text)
            if not match:
                name_parts = ent.text.split()
                if len(name_parts) > 1:
                    first_name = name_parts[0]
                    last_name = " ".join(name_parts[1:])
                    names.append((first_name, last_name))
    print("Names extracted (First Name, Last Name):")
    for first_name, last_name in names:
        print("First Name: "+first_name)
        print("Last Name: "+last_name)
    #
    data['fname'] = first_name
    data['lname'] = last_name
    age = None
    for ent in doc.ents:
        if ent.label_ == "DATE" or ent.label_ == "CARDINAL":
            if "Age" in ent.text or "age" in ent.text or "year" in ent.text or "years" in ent.text or "old" in ent.text or "years-old" in ent.text or "year-old" in ent.text:
                pattern = r'\d+'
                numbers = re.findall(pattern, ent.text)
                    
                for number in numbers:
                    # print(number)
                    age = number
            else:
                pattern = r'\d+'
                numbers = re.findall(pattern, ent.text)
                for number in numbers:
                    age = number          

    print("age=",age)
    
    #
    data['age'] = age
    time_period = None

main/templates/ShowCrime.html
{%load static%} {%block content%}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>CrimeAnalysis</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css'%}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css'%}" />
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico'%}" />
    <!-- MyStyle css -->
    <link rel="stylesheet" href="{% static 'assets/css/mystyle.css'%}" />


</head>

<body class="bg-white ">
  <div class="container-scroller bg-white ">
      {% include 'components/navbar.html' %}


    <!-- partial -->
    <div class="container-fluid page-body-wrapper" style="height: 100vh">
      <!-- partial:partials/_sidebar.html -->
      {% include 'components/sidebar.html' %}
      <!-- partial -->
      <div class="main-panel main-div bg-white">
        {%if msg%}
        <div class="alert alert-success alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{msg}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {%if err%}
        <div class="alert alert-danger alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{err}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
            <div class="text-center">
              Under development...!
            </div>
            
          <!-- page-body-wrapper ends -->
        </div>
    
          
        
        <footer class="footer">
          <div class="container-fluid d-flex justify-content-between">
            <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © </span>
            <span class="float-none float-sm-end mt-1 mt-sm-0 text-end">
              Free
            </span>
          </div>
        </footer>
      </div>
    </div>
    <!-- partial -->
  </div>



  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js'%}"></script>

  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js'%}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js'%}"></script>
  <script src="{% static 'assets/js/misc.js'%}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/file-upload.js'%}"></script>
  <script src="{% static 'assets/js/myjs.js'%}"></script>
  <!-- End custom js for this page -->
</div>
</body>

</html>
{%endblock%}

main/templates/UpdateCrime.html
{%load static%} {%block content%}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>CrimeAnalysis</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css'%}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css'%}" />
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico'%}" />
    <!-- MyStyle css -->
    <link rel="stylesheet" href="{% static 'assets/css/mystyle.css'%}" />


</head>

<body class="bg-white ">
  <div class="container-scroller bg-white ">
      {% include 'components/navbar.html' %}


    <!-- partial -->
    <div class="container-fluid page-body-wrapper" style="height: 100vh">
      <!-- partial:partials/_sidebar.html -->
      {% include 'components/sidebar.html' %}
      <!-- partial -->
      <div class="main-panel main-div bg-white">
        {%if msg%}
        <div class="text-center alert alert-success alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{msg}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {%if err%}
        <div class="text-center alert alert-danger alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{err}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
            <div class="content-wrapper d-flex align-items-center auth p-0" style="background-color:white !important;">
              
              <div class="row flex-grow bg-white">
                <div class=" mx-auto bg-white">
                  <div class="auth-form-light text-left py-1 bg-white ">
                    
                    <div class="brand-logo mt-4" style="text-align:center;">
                      {% comment %} <img src="{%static 'assets/images/logo.svg' %}"> {% endcomment %}
                      <h1>Select Crime to Update Record</h1>
    
                    </div>
                    <!-- <h6 class="font-weight-light">Signing up is easy. It only takes a few steps</h6> -->
                    
                    <div class="col-lg-8 col-10 m-auto">
                      <form action="/criminaldetail.html/" method="post">{% csrf_token %}
                        <table class="" style="" id="view_users">
                          <tr class="" style="border-bottom: 1px solid #36454F;">
                            <th class="p-2 pe-4 col-2  ">First Name</th>
                            <th class="p-2 pe-4 col-2  ">Last Name</th>
                            <th class="p-2 pe-4 col-2  ">Crime</th>                           
                          </tr>
                          {% for criminal in criminals_data %}
                          <tr class="" style="border-bottom: 1px solid #9b9b9b;">
                              <td class="p-2 pe-4 col-2">{{ criminal.first_name }}</td>
                              <td class="p-2 pe-4 col-2">{{ criminal.last_name }}</td>
                              <td class="p-2 pe-4 col-2">
                                {% for crime_type in criminal.crime_types %}
                                    <a href="{% url 'main:showupdate' param1=criminal.first_name param2=criminal.last_name param3=crime_type %}">
                                        {{ crime_type }}<br>
                                    </a>
                                {% endfor %}
                            </td>
                              
                          </tr>
                      {% endfor %}

                        </table>
                      </form> 
                    </div>
                        
                  </div>
                </div>
            <!-- content-wrapper ends -->
            </div>
            
          <!-- page-body-wrapper ends -->
        </div>
    
          
        
        <footer class="footer">
          <div class="container-fluid d-flex justify-content-between">
            <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © </span>
            <span class="float-none float-sm-end mt-1 mt-sm-0 text-end">
              Free
            </span>
          </div>
        </footer>
      </div>
    </div>
    <!-- partial -->
  </div>



  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js'%}"></script>

  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js'%}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js'%}"></script>
  <script src="{% static 'assets/js/misc.js'%}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/file-upload.js'%}"></script>
  <script src="{% static 'assets/js/myjs.js'%}"></script>
  <!-- End custom js for this page -->
</div>
</body>

</html>
{%endblock%}

main/templates/sampleurl.html
sampleurl.html page

main/templates/showupdatecrime.html
{%load static%} {%block content%}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>CrimeAnalysis</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css'%}" />
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css'%}" />
  <!-- endinject -->
  <!-- Layout styles -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css'%}" />
  <!-- End layout styles -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico'%}" />
    <!-- MyStyle css -->
    <link rel="stylesheet" href="{% static 'assets/css/mystyle.css'%}" />
  <style>
    .a{
      text-align : center;
      padding-right : 10%;
      font-size:30px;
    }

    thead{
      font-weight : bold;
    }
    table {
      border-collapse: separate;
      border-spacing: 0 2vh; 
    }

    td,tr{
        padding-right : 10vw;
        border-bottom: 1px solid black;
        margin-bottom : 20vh; 
    }


  </style>

  

</head>

<body>
 
  <div class="container-scroller">
      {% include 'components/navbar.html' %}

      
    <!-- partial -->
    <div class="container-fluid page-body-wrapper" style="height: 100vh">
      <!-- partial:partials/_sidebar.html -->
      {% include 'components/sidebar.html' %}
      <!-- partial -->
      <div class="main-panel main-div ">
        {%if msg%}
        <div class="alert alert-success alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{msg}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        {%if err%}
        <div class="alert alert-danger alert-dismissible fade show m-0 shadow ps-5" role="alert">
          <h3>
              {{err}}
          </h3>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
        <div class="content-wrapper">
          <div class="page-header">
            <h3 class="page-title">{{ status }}</h3>
            <h3 class="page-title"> Crime Details </h3>
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Forms</a></li>
                <li class="breadcrumb-item active" aria-current="page">Details</li>
              </ol>
            </nav>
          </div>
          <footer class="footer">
            <div class="container-fluid d-flex justify-content-between">
          <form class="form-sample" action="/showupdate_combined/" method="post" id="crime-form">{% csrf_token %}
          
            
            <div class="a">Type of Crime : {{ data.0.crime_types }}</div>
           
            
            <table>
              {% if data %}
              <thead>
                <tr>
                <td>FIR NUMBER</td>
                <td>DATE</td>
                <td>PLACE</td>
                <td>TIME</td>
                <td>SHOW</td>
                </tr>
              </thead>
              {% for c in data %}
              <tbody>
                <tr>
                <td>{{c.fir_no}}</td>
                <td>{{c.date_of_crime}}</td>
                <td>{{c.crime_spot}}</td>
                <td>{{c.time_period_of_crime}}</td>
                <td>
                  <a href="{% url 'main:displaycrime' param1=c.fir_no %}">
                    SHOW
                </a>
            </td>
                </tr>
              </tbody>
              {% endfor %}
              {%endif%}
            </table>
          </form>
            
           

        
            <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © </span>
            <span class="float-none float-sm-end mt-1 mt-sm-0 text-end">
              Free
            </span>
          </div>
        </footer>
      </div>
    </div>
    <!-- partial -->
  </div>
 

  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js'%}"></script>

  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js'%}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js'%}"></script>
  <script src="{% static 'assets/js/misc.js'%}"></script>
  <!-- endinject -->
  <!-- Custom js for this page -->
  <script src="{% static 'assets/js/file-upload.js'%}"></script>
  <script src="{% static 'assets/js/myjs.js'%}"></script>
  <!-- End custom js for this page -->
  
</div>


</body>

</html>
{%endblock%}